[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{access = "read", path = "watched_contracts.txt"}, { access = "read", path = "storage_layouts/"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config